name: mediscan
description: AI-Powered Prescription & Lab Report Interpreter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.6
  image_picker: ^1.0.4
  google_ml_kit: ^0.17.0
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  image: ^4.0.17
  permission_handler: ^11.0.1
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1
  carousel_slider: ^4.2.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  fl_chart: ^0.55.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  share_plus: ^12.0.1
  path_provider: ^2.0.15
  pdf: ^3.10.3
  printing: ^5.11.0
  flutter_svg: ^2.0.7
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/